default:
  server:
    # Server port listening
    port: 3301
    # Interval in minutes
    update_interval: 1
  average: 100
  targets:
    role1:
      name: 'github'
      domain: 'github.com'
    role2:
      name: 'google'
      domain: 'google.com'
    role3:
      name: 'cloudflare'
      domain: 'cloudflare.com'